# Generated by Django 4.0.3 on 2022-05-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='photo',
        ),
    ]
